---
title: "Homework 8"
format: html
embed-resources: true
author: "Luke Monsma"
---

[Back](https://lukemonsma.github.io/DATA304/)

[Assignment](https://calvin-data304.netlify.app/hw/hw08-wrangling-for-graphics.html)

## Exercise 1

```{r}
library(vegabrite)
library(dplyr)
library(readr)
library(tidyr)
supply_data_wide <- read.csv(file = "https://calvin-data304.netlify.app/data/swd-lets-practice-ex-2-3.csv")

supply_data_wide <- supply_data_wide |>
  mutate(capacity = parse_number(capacity), demand = parse_number(demand))

supply_data_long <- supply_data_wide |>
  pivot_longer(cols = c("capacity", "demand"), names_to = "type", values_to = "value")
```

```{r}
vl_chart() |>
  vl_mark_bar() |>
  vl_encode_y("value:Q", title = "") |>
  vl_encode_x("date:N", title = "Month") |>
  vl_encode_xOffset("type:N") |>
  vl_sort_xOffset("descending") |>
  vl_encode_color("type:N", title = "") |>
  vl_add_data(supply_data_long)
```

```{r}
vl_chart() |>
  vl_mark_line() |>
  vl_encode_y("value:Q", title = "") |>
  vl_encode_x("date:N", title = "Month") |>
  vl_encode_color("type:N", title = "") |>
  vl_add_data(supply_data_long)
```

```{r}
vl_chart() |>
  vl_mark_bar() |>
  vl_encode_order(field = "type:N", sort = "ascending") |>
  vl_encode_y("value:Q", title = "") |>
  vl_encode_x("date:N", title = "Month") |>
  vl_encode_color("type:N", title = "") |>
  vl_encode_size("type:N", legend = FALSE) |>
  vl_scale_size(domain = c("demand", "capacity"), range = c(10, 15)) |>
  vl_add_data(supply_data_long)
```

```{r}
vl_chart() |>
  vl_mark_bar() |>
  vl_encode_order(field = "type:N", sort = "ascending") |>
  vl_encode_y("value:Q", title = "") |>
  vl_encode_x("date:N", title = "Month") |>
  vl_encode_color("type:N", title = "") |>
  vl_add_data(supply_data_long)
```

```{r 'hello'}
capacity_points <- vl_chart() |>
  vl_mark_point() |>
  vl_encode_y("capacity:Q") |>
  vl_encode_color(value = "blue")

demand_points <- vl_chart() |>
  vl_mark_point() |>
  vl_encode_y("demand:Q") |>
  vl_encode_color(value = "red")

bars <- vl_chart() |>
  vl_mark_bar() |>
  vl_encode_y("capacity:Q") |>
  vl_encode_y2("demand:Q") |>
  vl_encode_color(value = "gray") |>
  vl_encode_size(value = 5)

vl_layer(bars, capacity_points, demand_points) |>
  vl_encode_x("date:N", title = "Month") |>
  vl_encode_y(type = "quantitative") |>
  vl_add_data(supply_data_wide)
```

```{r}
vl_chart() |>
  vl_mark_line() |>
  vl_calculate(calculate = "datum.demand - datum.capacity", as = "diff") |>
  vl_encode_y("diff:Q", title = "Unmet Demand") |>
  vl_encode_x("date:N", title = "Month") |>
  vl_add_data(supply_data_wide)
```


```{r}
#| fig-cap: "Caption"
vl_chart() |>
  vl_mark_point() |>
  vl_pivot(pivot = "year", value = "perc", groupby = list("job", "sex")) |>
  vl_encode_x("1850:Q") |>
  vl_encode_y("2000:Q") |>
  vl_scale_x(type = "symlog", constant = 0.00001) |>
  vl_scale_y(type = "symlog", constant = 0.00001) |>
  vl_facet_column(field = "sex:N", title = "") |>
  vl_encode_tooltip_array(list("job", "1850", "2000")) |>
  vl_add_properties(title = "Jobs") |>
  vl_add_data_url("https://cdn.jsdelivr.net/npm/vega-datasets@2.8.0/data/jobs.json")
```
